server:
  address: 0.0.0.0:8000
jobs:
  - backup-type: 2
    schedule: 0 1 * * *
    src-dirs:
      - d:\sample\dir1
      - d:\sample\dir2
      - d:\sample\abc
    storage:
#      protocol: 1
#      dir: d:\backup
      protocol: 1
      host: 10.10.10.10
      port: 22
      username: ddd
      password: ddd
      dir: d:\backup
#      dir: /data/backup
    ignore:
      - .tar
  - backup-type: 2
    schedule: 0 5 * * *
    src-dirs:
      - D:\sample\dir2
    storage:
      protocol: 1
      dir: d:\backup
